version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: time-series-db
    restart: always
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: time_series_app
      POSTGRES_PASSWORD: SecrEtPaSsWoRd
      POSTGRES_DB: time_series
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
